spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.kaciner.cn
          predicates:
            - Query=url,kaciner

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq